---
exclude_paths:
  - test
detectors:
  DuplicateMethodCall:
    enabled: false
  NilCheck:
    enabled: false
  LongParameterList:
    max_params: 4
  RepeatedConditional:
    enabled: false
  UtilityFunction:
    exclude:
      - CodelessCode::Filters::Headers::Base
      - CodelessCode::Filters::Date
